### ISSUE TITLE
 react-native-flipper-apollo-devtools, dist folder is empty v0.0.1

### ISSUE THREAD

**Issue by MikePodgorniy** [plrdev/react-native-flipper-apollo-devtools#2]
"react-native-flipper-apollo-devtools": "0.0.1",

➜  react-native-flipper-apollo-devtools git:(develop) ✗ ls -la 
total 16
drwxr-xr-x     6 mike  staff    192  7 сен 11:01 .
drwxr-xr-x  1415 mike  staff  45280  7 сен 11:53 ..
-rw-r--r--     1 mike  staff   1070  7 сен 10:41 LICENSE
drwxr-xr-x     3 mike  staff     96  7 сен 11:01 dist
-rw-r--r--     1 mike  staff    930  7 сен 10:41 package.json
drwxr-xr-x     3 mike  staff     96  7 сен 11:01 src

➜  dist git:(develop) ✗ ls -la 
total 8
drwxr-xr-x  3 mike  staff   96  7 сен 11:01 .
drwxr-xr-x  6 mike  staff  192  7 сен 11:01 ..
-rw-r--r--  1 mike  staff  250  7 сен 10:41 index.js

**Comment by ManAnRuck** [comment]
same issue


content of the index
```js
'use strict'

if (process.env.NODE_ENV === 'production') {
  module.exports = require('./react-native-flipper-apollo-devtools.cjs.production.min.js')
} else {
  module.exports = require('./react-native-flipper-apollo-devtools.cjs.development.js')
}
```

is requiring not existing files @plrdev 

<img width="1430" alt="Bildschirmfoto 2020-09-23 um 13 50 52" src="https://user-images.githubusercontent.com/2183135/94008778-d7c91e80-fda3-11ea-8526-3421fb1e202b.png">

also type definitions are not exported
