### ISSUE TITLE
Dist folder is still empty v0.0.1

### ISSUE THREAD

**Issue by AndrewShapovalov** [plrdev/react-native-flipper-apollo-devtools#5]
Hey and thanks for all your efforts! 

Dist folder is still empty after installation package.  
![Screenshot 2020-10-01 at 19 02 14](https://user-images.githubusercontent.com/26417506/94834119-a3470980-0418-11eb-9b74-11b9140694c9.png)

Seems that you haven't built project before publish to npm. I would recommend you to add additional script to `packaje.json` file: `"prepublishOnly": "npm run build"` and publish project again.

Also, I would recommend you to update a few lines in `README.md` file.
1. We can save `react-native-flipper-apollo-devtools` for our projects as dev dependency (`npm install --save-dev react-native-flipper-apollo-devtools`);
2. So, as we don't need it on production, we can import and enable apollo devtools for flipper like so:
![Screenshot 2020-10-01 at 18 41 48](https://user-images.githubusercontent.com/26417506/94831912-f53a6000-0415-11eb-952b-b7fa5fdf13a9.png)

**Comment by plrdev** [comment]
I have been a bit busy with work, you seem to have a good idea what needs to be done, care to make a PR out of this @AndrewShapovalov :) I can merge it fast then.

**Comment by pontusab** [comment]
I added a PR fixing this, when merged, can you do a new release including the dist, please? 🥇

**Comment by plrdev** [comment]
0.0.2 released with the changes to building when publishing, hope this makes it work! Thanks @pontusab 

Readme change PR would still be appreciated @AndrewShapovalov - it's a good idea.

**Comment by plrdev** [comment]
I will close this issue though as that has been resolved.

**Comment by pontusab** [comment]
can confirm that 0.0.2 works!
